### Инструкция по выполнению

    1. Загрузите данные close_prices.csv. В этом файле приведены цены акций 30 компаний на закрытии торгов за каждый день периода.
    2. На загруженных данных обучите преобразование PCA с числом компоненты равным 10. Скольких компонент хватит, чтобы объяснить 90% дисперсии?
    3. Примените построенное преобразование к исходным данным и возьмите значения первой компоненты.
    4. Загрузите информацию об индексе Доу-Джонса из файла djia_index.csv. Чему равна корреляция Пирсона между первой компонентой и индексом Доу-Джонса?
    5. Какая компания имеет наибольший вес в первой компоненте? Укажите ее название с большой буквы.

Если ответом является нецелое число, то целую и дробную часть необходимо разграничивать точкой, например, 0.42. При необходимости округляйте дробную часть до двух знаков.

Ответ на каждое задание — текстовый файл, содержащий ответ в первой строчке. Обратите внимание, что отправляемые файлы не должны содержать перевод строки в конце. Данный нюанс является ограничением платформы Coursera. Мы работаем над тем, чтобы убрать это ограничение.

In [1]:
import pandas as pd
from pathlib import Path
path = Path.cwd()
path = path.joinpath('../data/raw/HSE_ML_week4')

data = pd.read_csv(path.joinpath('close_prices.csv'))
data.head(10)

,date,AXP,BA,CAT,CSCO,CVX,DD,DIS,GE,GS,...,PFE,PG,T,TRV,UNH,UTX,V,VZ,WMT,XOM
0,2013-09-23,76.440002,117.510002,85.029999,24.270000,125.519997,59.409999,64.750000,24.280001,165.250000,...,28.799999,79.279999,34.220001,86.379997,71.820000,109.419998,196.240005,47.980000,76.419998,87.750000
1,2013-09-24,76.070000,119.000000,85.110001,24.139999,124.489998,59.319997,64.320000,24.320000,162.970001,...,28.709999,78.620003,34.090000,85.870003,72.320000,110.000000,193.339996,47.270000,75.750000,87.360001
2,2013-09-25,75.989998,118.510002,84.500000,24.430000,124.070000,59.319997,64.449997,24.230000,162.309998,...,28.490000,77.720001,34.049999,85.980003,71.980003,109.260002,191.559998,46.950001,74.650002,87.139999
3,2013-09-26,76.320000,119.379997,84.199997,23.770000,123.489998,59.509996,65.239998,24.250000,162.289993,...,28.520000,78.050003,34.230000,85.830002,72.160004,109.660004,193.559998,47.669998,74.620003,87.070000
4,2013-09-27,75.889999,118.739998,83.800003,23.330000,122.639999,59.009995,65.190002,24.049999,159.850006,...,28.879999,77.209999,33.980000,85.410004,71.989998,109.360001,193.050003,47.000000,74.360001,86.900002
5,2013-09-30,75.519997,117.500000,83.400002,23.430000,121.500000,58.560000,64.489998,23.889999,158.210007,...,28.730000,75.589996,33.820000,84.769997,71.610001,107.820000,191.100006,46.669998,73.959999,86.040001
6,2013-10-01,75.930000,117.750000,83.760002,23.240000,121.320000,58.689999,64.830002,24.170000,159.000000,...,28.889999,76.160004,34.060001,84.660004,72.580002,107.379997,193.220001,46.990002,73.589996,86.000000
7,2013-10-02,74.580002,117.839996,84.070000,23.320000,120.830002,58.989999,64.879997,24.330000,158.669998,...,29.010000,75.930000,33.939999,84.480003,72.570000,104.980003,191.820007,46.790001,73.720001,86.080002
8,2013-10-03,74.019997,115.239998,83.970001,23.010000,118.250000,57.759995,64.019997,24.100000,156.850006,...,28.770000,75.839996,33.639999,84.059998,72.519997,103.690002,188.649994,47.009998,73.160004,85.500000
9,2013-10-04,74.309998,117.199997,84.199997,23.020000,118.129997,58.649998,65.300003,24.049999,156.550003,...,29.000000,76.019997,33.750000,84.680000,72.989998,104.269997,190.479996,47.099998,72.800003,86.320000

In [6]:
import numpy as np
from sklearn.decomposition import PCA

X = data.copy()
del X['date']

pca = PCA(n_components=10)
pca.fit(X)
np.add.accumulate(pca.explained_variance_ratio_)

array([0.73897118, 0.84904287, 0.89899376, 0.92774295, 0.94989743,
       0.9692132 , 0.97596173, 0.98210264, 0.98530858, 0.98836469])

In [9]:
file = open('/home/topcoder2k/HSE_ML/HSE_ML_week4_answers/pca_90.txt', 'w')
file.write('4')
file.close()

In [36]:
X_reduced = pca.transform(X)
component1 = X_reduced[:, 0]

djia_index = pd.read_csv(path.joinpath('djia_index.csv'))
np.corrcoef(component1, djia_index['^DJI'])

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [37]:
file = open('/home/topcoder2k/HSE_ML/HSE_ML_week4_answers/corrcoef.txt', 'w')
file.write('0.91')
file.close()

In [46]:
max_var = abs(pca.components_[0]).max()

for i in range(pca.components_[0].size):
    if abs(pca.components_[0][i] - max_var) < 0.001:
        print(i)

26

In [47]:
file = open('/home/topcoder2k/HSE_ML/HSE_ML_week4_answers/important_company.txt', 'w')
file.write('V')
file.close()